{{ if eq .chezmoi.os "darwin" -}}
[".iterm2_shell_integration.zsh"]
  type = "file"
  url = "https://iterm2.com/shell_integration/zsh"
  refreshPeriod = "24h"
{{ end -}}
[".oh-my-zsh"]
  type = "archive"
  url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "24h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "24h"
[".oh-my-zsh/custom/plugins/atuin/atuin.plugin.zsh"]
  type = "file"
  url = "https://raw.githubusercontent.com/atuinsh/atuin/main/atuin.plugin.zsh"
  refreshPeriod = "24h"
{{- if or (findExecutable "starship" (list ".local/bin")) (not (lookPath "starship")) }}
  {{- $arch := .chezmoi.arch }}
  {{- $runtime := "" }}
  {{- if eq .chezmoi.os "linux" }}{{ $runtime = "-musl" }}{{ end }}
  {{- if eq $arch "arm64" }}
    {{- $arch = "aarch64" }}
  {{- else if eq $arch "arm" }}
    {{- $runtime = "-musleabihf" }}
  {{- else if eq $arch "amd64" }}
    {{- $arch = "x86_64" }}
    {{- if eq .chezmoi.os "linux" }}
      {{- if eq .chezmoi.osRelease.id "alpine" }}
        {{- $runtime = "-musl" }}
      {{- else }}
        {{- $runtime = "-gnu" }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- $archive_url := gitHubLatestReleaseAssetURL "starship/starship" (printf "starship-%s-*-%s%s.tar.gz" $arch .chezmoi.os $runtime) }}
  {{- if ne $archive_url "" }}
[".local/bin/starship"]
  type = "archive-file"
  url = {{ quote $archive_url }}
  path = "starship"
  refreshPeriod = "24h"
  {{- end }}
{{- end }}
{{- if or (findExecutable "eza" (list ".local/bin")) (not (lookPath "eza")) }}
  {{- $arch := .chezmoi.arch }}
  {{- $runtime := "" }}
  {{- if eq $arch "arm64" }}
    {{- $arch = "aarch64" }}
  {{- else if eq $arch "amd64" }}
    {{- $arch = "x86_64" }}
  {{- end }}
  {{- if eq .chezmoi.os "linux" }}
    {{- if eq .chezmoi.osRelease.id "alpine" }}
      {{- $runtime = "musl" }}
    {{- else if eq $arch "arm" }}
      {{- $runtime = "gnueabihf" }}
    {{- else }}
      {{- $runtime = "gnu" }}
    {{- end }}
  {{- end }}
  {{- $archive_url := gitHubLatestReleaseAssetURL "eza-community/eza" (printf "eza_%s-*-%s-%s.tar.gz" $arch .chezmoi.os $runtime) }}
  {{- if ne $archive_url "" }}
[".local/bin/eza"]
  type = "archive-file"
  url = {{ quote $archive_url }}
  path = "./eza"
  refreshPeriod = "24h"
  {{- end }}
{{- end }}
{{- if or (findExecutable "fzf" (list ".local/bin")) (not (lookPath "fzf")) }}
  {{- $arch := .chezmoi.arch }}
  {{- if eq $arch "arm" }}
    {{- $arch = "armv7" }}
  {{- end }}
  {{- $archive_url := gitHubLatestReleaseAssetURL "junegunn/fzf" (printf "fzf-*-%s_%s.tar.gz" .chezmoi.os $arch) }}
  {{- if ne $archive_url "" }}
[".local/bin/fzf"]
  type = "archive-file"
  url = {{ quote $archive_url }}
  path = "fzf"
  refreshPeriod = "24h"
  {{- end }}
{{- end }}
{{- if or (findExecutable "rg" (list ".local/bin")) (not (lookPath "rg")) }}
  {{- $arch := .chezmoi.arch }}
  {{- $runtime := "" }}
  {{- if eq $arch "arm64" }}
    {{- $arch = "aarch64" }}
  {{- else if eq $arch "amd64" }}
    {{- $arch = "x86_64" }}
  {{- else if eq $arch "arm" }}
    {{- $arch = "armv7" }}
  {{- end }}
  {{- if eq .chezmoi.os "linux" }}
    {{- if eq .chezmoi.arch "amd64" }}
      {{- $runtime = "-musl" }}
    {{- else if eq .chezmoi.osRelease.id "alpine" }}
      {{- $runtime = "-musl" }}
    {{- else if eq .chezmoi.arch "arm" }}
      {{- $runtime = "-musleabihf" }}
    {{- else }}
      {{- $runtime = "-gnu" }}
    {{- end }}
  {{- end }}
  {{- $archive_url := gitHubLatestReleaseAssetURL "BurntSushi/ripgrep" (printf "ripgrep-*-%s-*-%s%s.tar.gz" $arch .chezmoi.os $runtime) }}
  {{- if ne $archive_url "" }}
[".local/bin/rg"]
  type = "archive-file"
  url = {{ quote $archive_url }}
  stripComponents = 1
  path = "rg"
  refreshPeriod = "24h"
  {{- end }}
{{- end }}
{{- if or (findExecutable "atuin" (list ".local/bin")) (not (lookPath "atuin")) }}
  {{- $arch := .chezmoi.arch }}
  {{- $runtime := "" }}
  {{- if eq $arch "arm64" }}
    {{- $arch = "aarch64" }}
  {{- else if eq $arch "amd64" }}
    {{- $arch = "x86_64" }}
  {{- end }}
  {{- if eq .chezmoi.os "linux" }}
    {{- if eq .chezmoi.osRelease.id "alpine" }}
      {{- $runtime = "-musl" }}
    {{- else }}
      {{- $runtime = "-gnu" }}
    {{- end }}
  {{- end }}
  {{- $archive_url := gitHubLatestReleaseAssetURL "atuinsh/atuin" (printf "atuin-%s-*-%s%s.tar.gz" $arch .chezmoi.os $runtime) }}
  {{- if ne $archive_url "" }}
[".local/bin/atuin"]
  type = "archive-file"
  url = {{ quote $archive_url }}
  stripComponents = 1
  path = "atuin"
  refreshPeriod = "24h"
  {{- end }}
{{- end }}
{{- if or (findExecutable "zoxide" (list ".local/bin")) (not (lookPath "zoxide")) }}
  {{- $arch := .chezmoi.arch }}
  {{- $runtime := "" }}
  {{- if eq $arch "arm64" }}
    {{- $arch = "aarch64" }}
  {{- else if eq $arch "amd64" }}
    {{- $arch = "x86_64" }}
  {{- end }}
  {{- if eq .chezmoi.os "linux" }}
    {{- $runtime = "-musl" }}
    {{- if or (eq .chezmoi.arch "arm") (eq .chezmoi.arch "armv7") }}
      {{- $runtime = "-musleabihf" }}
    {{- end }}
  {{- end }}
  {{- $archive_url := gitHubLatestReleaseAssetURL "ajeetdsouza/zoxide" (printf "zoxide-*-%s-*-%s%s.tar.gz" $arch .chezmoi.os $runtime) }}
  {{- if ne $archive_url "" }}
[".local/bin/zoxide"]
  type = "archive-file"
  url = {{ quote $archive_url }}
  path = "zoxide"
  refreshPeriod = "24h"
  {{- end }}
{{- end }}
{{- if eq .role.designation "personal" }}
[".password-store/.extensions/file.bash"]
  type = "file"
  url = "https://raw.githubusercontent.com/jamebus/pass-file/refs/heads/master/file.bash"
  executable = true
  refreshPeriod = "24h"
{{- end }}
{{- if not (lookPath "ghostty") }}
[".terminfo"]
  type = "archive"
  url = "https://hicag.link/ghostty-terminfo"
  exact = true
  stripComponents = 1
  refreshPeriod = "24h"
{{- end }}
