{{ if eq .chezmoi.os "darwin" -}}
[".iterm2_shell_integration.zsh"]
  type = "file"
  url = "https://iterm2.com/shell_integration/zsh"
  refreshPeriod = "24h"
{{ end -}}
[".oh-my-zsh"]
  type = "archive"
  url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "24h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "24h"
{{- if not (lookPath "starship") }}
  {{- $arch := .chezmoi.arch }}
  {{- $runtime := "" }}
  {{- if eq .chezmoi.os "linux" }}{{ $runtime = "-musl" }}{{ end }}
  {{- if eq $arch "arm64" }}
    {{- $arch = "aarch64" }}
  {{- else if eq $arch "arm" }}
    {{- $runtime = "-musleabihf" }}
  {{- else if eq $arch "amd64" }}
    {{- $arch = "x86_64" }}
    {{- if eq .chezmoi.os "linux" }}
      {{- if eq .chezmoi.osRelease.id "alpine" }}
        {{- $runtime = "-musl" }}
      {{- else }}
        {{- $runtime = "-gnu" }}
      {{- end }}
    {{- end }}
  {{- end }}
[".local/bin/starship"]
  type = "archive-file"
  url = {{ gitHubLatestReleaseAssetURL "starship/starship" (printf "starship-%s-*-%s%s.tar.gz" $arch .chezmoi.os $runtime) | quote }}
  path = "starship"
  refreshPeriod = "24h"
{{- end }}
{{- if lookPath "vim" }}
[".vim/uri-ref-20061101.vim"]
  type = "file"
  url = "https://www.vim.org/scripts/download_script.php?src_id=6358"
  checksum.sha256 = "c2a60ca3bfea1fdc6ca5317be356b27781ec0a3f975b983c8fd5284c16be27aa"
{{- end }}
