#!/bin/sh

set -eu

cd "${0%/*}"

. ./vars

if [ ! -d "$ZSH" ]; then
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" \
	      --unattended --skip-chsh --keep-zshrc
fi

if [ ! -d "${ZSH}/custom/themes/powerlevel10k" ]; then
	git -C "${ZSH}/custom/themes" clone --depth=1 \
	                              https://github.com/jamebus/powerlevel10k.git
fi

if [ -n "${ITERM_PROFILE:-}" ]; then
	install -v -m 0400 dot.iterm2_shell_integration.zsh \
	                   "${zdot}/.iterm2_shell_integration.zsh"
fi

install -v -m 0400 dot.zshrc    "${zdot}/.zshrc"
install -v -m 0400 dot.p10k.zsh "${zdot}/.p10k.zsh"

if [ -d "${HOME}/.pagpapanatili/profiles.d" ]; then
	install -v -m 0400 zzz-home.yaml "${HOME}/.pagpapanatili/profiles.d"
fi
