#!/bin/sh

set -eu

cd "${0%/*}"

. ./vars

if [ ! -d "$ZSH" ]; then
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" \
	      --unattended --skip-chsh --keep-zshrc
fi

if ! command -v starship >/dev/null 2>&1; then
	PATH="${PATH}:${HOME}/.starship/bin"
	export PATH

	if ! command -v starship >/dev/null 2>&1; then
		install -d -m 0755 "${HOME}/.starship/bin"
		curl -sS https://starship.rs/install.sh | \
		  env FORCE=1 BIN_DIR="${HOME}/.starship/bin" sh
	fi
fi

if [ -n "${ITERM_PROFILE:-}" ]; then
	install -v -m 0400 dot.iterm2_shell_integration.zsh \
	                   "${zdot}/.iterm2_shell_integration.zsh"
fi

install -v -m 0400 dot.zshrc "${zdot}/.zshrc"
install -v -d -m 0755 "${HOME}/.config"
install -v -m 0400 starship.toml "${HOME}/.config"

if [ -d "${HOME}/.pagpapanatili/profiles.d" ]; then
	install -v -m 0400 zzz-home.yaml "${HOME}/.pagpapanatili/profiles.d"
fi
