#!/bin/sh

# shellcheck disable=SC1090
. "$(ayusin --common)"
# shellcheck disable=SC2034
task_description='puppet-lint update'

task_start

command -v gem >/dev/null 2>&1                || task_skip
$DRYRUN gem update puppet-lint --user-install || task_fail

task_end
