#!/bin/sh

# shellcheck disable=SC1090
. "$(ayusin --common)"
# shellcheck disable=SC2034
task_description='Update dotfiles'

task_start

command -v chezmoi >/dev/null 2>&1 || task_skip
$DRYRUN chezmoi update             || task_fail

task_end
