#!/bin/sh

# shellcheck disable=SC1090
. "$(ayusin --common)"
# shellcheck disable=SC2034
task_description='Docker prune'

task_start
task_lastrun_days 30              || task_skip
command -v docker >/dev/null 2>&1 || task_skip

rc=0

$DRYRUN docker container prune -f                   || rc=$((rc + 1))
$DRYRUN docker image     prune -f -a                || rc=$((rc + 1))
$DRYRUN docker volume    prune -f                   || rc=$((rc + 1))
$DRYRUN docker buildx    prune -f --builder=builder || rc=$((rc + 1))

test $rc -eq 0 || task_fail

task_update_lastrun
task_end
