#!/bin/sh

# shellcheck disable=SC1090
. "$(ayusin --common)"
# shellcheck disable=SC2034
task_description='pass git push'

task_start

command -v pass >/dev/null 2>&1 || task_skip
$DRYRUN pass git push           || task_fail

task_end
