#!/bin/sh

# This is set in common, but shellcheck doesn't detect it
set -e

# shellcheck disable=SC1090
. "$(ayusin --common)"
# shellcheck disable=SC2034
task_description='Update LazyVim'

task_start

command -v nvim >/dev/null 2>&1                          || task_skip
test -f "${HOME}/.config/nvim/lazy-lock.json"            || task_skip
$DRYRUN nvim --headless '+Lazy! sync' '+Lazy! clean' +qa || task_fail

task_end
